services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      DBT_PROFILES_DIR: /app/dbt
    working_dir: /app
    volumes:
      - .:/app
    stdin_open: true
    tty: true
